version: '3'

services:
  db:
    image: mysql:latest
    container_name: petsfinder_db
    environment:
      - DB_HOST: db
      - MYSQL_DATABASE: petsfinder
      - MYSQL_USER: root
      - MYSQL_PASSWORD: root
      - MYSQL_ROOT_PASSWORD: root
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    env_file:
      - .env
      
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "python src/PetsFinder/manage.py wait_for_db && python src/PetsFinder/manage.py migrate && python src/PetsFinder/manage.py runserver 0.0.0.0:8080"
    container_name: petsfinder_app
    image: petsfinder_app
    environment:
      - DB_HOST: db
      - MYSQL_DATABASE: petsfinder
      - MYSQL_USER: root
      - MYSQL_PASSWORD: root
      - MYSQL_ROOT_PASSWORD: root
    ports:
      - "8080:8080"
    depends_on:
      - db
    links:
      - db
    env_file:
      - .env

volumes:
  db_data:
