name: Build and Push latest release

on:
  push:
    branches:
      - main

jobs:
  build:
    
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ${{ secrets.DOCKERHUB_USERNAME }}/pets-finder:latest
    
      - name: Push the Docker image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/pets-finder:latest
